[package]
name = "cec2uinput"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
anyhow = "1.0"

libcec-sys = "8.0.0"
uinput = "0.1.3"



