[package]
name = "cec2uinput"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml_ng = "0.10"
anyhow = "1.0"

cec-rs = "12.0.0"
uinput = "0.1.3"
clap = { version = "4.5.4", features = ["derive"] }

