device_name: "CM5-CEC-Bridge"
cec_version: "1.4"        # CEC version: 1.3, 1.4, or 2.0
mappings:
  # Example usages (supported syntaxes):
  # "CTRL[c], enter"  -> press Ctrl+C, then press Enter
  # "ALT[a,f]"        -> press Alt, then A, then F while Alt held, then release Alt
  # "CTRL+ALT+del"    -> press Ctrl and Alt, then press Delete while both modifiers held, then release modifiers
  # You can use aliases like: del, ins, pgup, pgdown, return, spacebar

  # Basic Navigation
  Up: "mount_up"               # CEC Up button -> Up arrow key
  Down: "mount_down"           # CEC Down button -> Down arrow key
  Left: "mount_left"           # CEC Left button -> Left arrow key
  Right: "mount_right"         # CEC Right button -> Right arrow key
  Select: "mouse_click_left"   # CEC Select button -> Enter key
  Exit: "esc"                  # CEC Exit button -> Escape key

  # Color Buttons
  F2Red: "f1"         # CEC Red button -> F1 key
  F3Green: "f2"       # CEC Green button -> F2 key
  F4Yellow: "f3"      # CEC Yellow button -> F3 key
  F1Blue: "f4"        # CEC Blue button -> F4 key

  # Numbers
  Number0: "0"        # CEC Number 0 button -> 0 key
  Number1: "1"        # CEC Number 1 button -> 1 key
  Number2: "2"        # CEC Number 2 button -> 2 key
  Number3: "3"        # CEC Number 3 button -> 3 key
  Number4: "4"        # CEC Number 4 button -> 4 key
  Number5: "5"        # CEC Number 5 button -> 5 key
  Number6: "6"        # CEC Number 6 button -> 6 key
  Number7: "7"        # CEC Number 7 button -> 7 key
  Number8: "8"        # CEC Number 8 button -> 8 key
  Number9: "9"        # CEC Number 9 button -> 9 key

  # More examples:
  #
  # Modifier Sequences
  #  Number0: "ctrl+alt+del"  # Press Ctrl and Alt, then Delete
  #  Number1: "shift+tab"     # Press Shift, then Tab
  #  Exit: "alt+f4"           # Press Alt, then F4
  #
  # Bracket Lists
  #  Number2: "ctrl+[a,b,c]"  # Press Ctrl, then A, B, C in sequence
  #  Number3: "alt+[x,y]"     # Press Alt, then X, Y in sequence
  #
  # Simultaneous Keys
  #  Number4: "playpause"     # Simultaneously press Play and Pause
  #  Number5: "volumemute"    # Simultaneously press Volume Up and Volume Down
  #
  # Mouse mappings (examples)
  # Use the following mapping tokens to control a virtual mouse created by the bridge:
  #   mouse_right  - move cursor right
  #   mouse_left   - move cursor left
  #   mouse_up     - move cursor up
  #   mouse_down   - move cursor down
  #   mouse_click_left  (aliases: mouse_left_click, mouse_lclick)  - left button click
  #   mouse_click_right (aliases: mouse_right_click, mouse_rclick) - right button click
  #
  # Movement uses exponential steps per repeated mapped event: [1, 10, 50, 100, 500] pixels.
  # The step counter for each direction resets after 500 milliseconds of idle mouse activity.
  #
  # Example mappings:
  #  Right: "mouse_right"           # map CEC Right to mouse move right (press repeatedly to accelerate)
  #  Left: "mouse_left"             # map CEC Left to mouse move left
  #  Select: "mouse_click_left"     # map Select to left click
  #
  # You can add these under mappings to enable mouse behavior.
